-- Insert default settings with message templates
INSERT INTO "settings" ("agency_name", "contact_name", "message_templates", "brand_color", "updated_at")
VALUES (
  'GoSite Agency',
  'Youssef',
  '{
    "intro": "Bonjour {{firstName}} 👋\n\nJe me permets de vous contacter car je suis tombé(e) sur votre {{sector}} à {{city}} et j''ai été vraiment impressionné(e) par ce que vous proposez{{#if rating}} (note {{rating}}/5 sur Google — bravo !){{/if}}{{#if cuisine}}, notamment votre cuisine {{cuisine}}{{/if}}.\n\nJ''ai remarqué que vous n''avez pas encore de site web, et c''est un vrai manque aujourd''hui : la majorité de vos futurs clients vous cherchent sur Google avant de venir.\n\n👉 J''ai préparé **gratuitement** une démo personnalisée de ce que pourrait être votre site web professionnel. Vous la trouverez ici :\n{{demo_url}}\n\nHâte d''avoir votre avis 😊\n{{#if phone}}Si vous préférez qu''on en parle de vive voix : {{phone}}{{/if}}",
    "demo": "Comme promis, voici la démo personnalisée pour **{{name}}** :\n🌐 {{demo_url}}\n\n✨ Ce que j''ai mis en avant :\n• Votre {{sector}} situé à {{city}}{{#if cuisine}}\n• Votre spécialité {{cuisine}}{{/if}}{{#if rating}}\n• Votre note {{rating}}/5 sur Google{{/if}}\n• Un design moderne adapté à votre image\n• Un bouton pour vous appeler en 1 clic{{#if openingHours}}\n• Vos horaires : {{openingHours}}{{/if}}\n• Une carte Google Maps intégrée\n\nLe site est responsive (parfait sur mobile) et optimisé pour Google. Vous voyez ce que ça donnerait concrètement ?",
    "quote": "Suite à votre intérêt pour le site, voici ma proposition :\n\n📦 **{{name}} — Site web professionnel clé en main**\n\n💰 **Tarif : {{price}}**\n{{features}}\n\nPour accepter et démarrer aujourd''hui :\n💳 {{payment_url}}\n\n⚠️ Cette offre est valable 7 jours. Au plaisir de travailler ensemble !",
    "delivery": "🎉 **Votre site est en ligne !**\n\nBonjour {{firstName}}, votre site web professionnel est désormais accessible à l''adresse :\n🌐 {{final_site_url}}\n\n✅ Hébergement inclus pour 1 an\n✅ Domaine personnalisé\n✅ Certificat SSL (sécurisé HTTPS)\n✅ Optimisé pour Google\n\n📊 Un petit guide PDF avec toutes les instructions pour le modifier vous-même est en pièce jointe.\n\nN''hésitez pas si vous avez la moindre question, je reste disponible !\nBelle continuation à {{name}} 🚀",
    "thanks": "Un grand merci {{firstName}} 🙏\n\nVotre confiance me touche sincèrement. Quelques infos pour la suite :\n\n📅 Je vous recontacte dans 3 mois pour voir comment se passe le site et s''il y a des ajustements à faire.\n\n💌 Si dans votre entourage un commerce a besoin d''un site, n''hésitez pas à me recommander — je vous offrirai une réduction sur votre abonnement annuel en guise de remerciement.\n\nAu plaisir, et encore merci !\nBelle journée ☀️",
    "payment_received": "Bonjour {{firstName}} 👋\n\nBien reçu votre paiement, un grand merci pour votre confiance ! 🎉\n\nLe développement et la mise en ligne du site web pour *{{name}}* sont désormais lancés.\n\nVous recevrez le lien final de votre site internet ici même sous *24h*.\n\nSi vous avez la moindre question d''ici là, n''hésitez pas à me contacter.",
    "followup": "Bonjour {{firstName}} 👋\n\nJe me permets de revenir vers vous au sujet de la démo de site web que je vous avais envoyée pour *{{name}}*.\n\nAvez-vous eu le temps de la regarder ? Si ce n''est pas le bon moment, pas de souci — je peux aussi simplement vous appeler pour en discuter en 5 minutes.\n\nSinon, dites-moi ce qui vous ferait hésiter (budget, délais, fonctionnalités...) et j''adapte la proposition."
  }'::jsonb,
  '#E8622A',
  NOW()
);
